import type { AppUser, Booking, Coupon, Dispute, Venue } from "./types";

// Helper to produce ISO date strings relative to "today"
function futureDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}
function pastDate(days: number): string {
  return futureDate(-days);
}

export const SEED_USERS: AppUser[] = [
  {
    id: "u-cust-1",
    name: "Ananya Sharma",
    email: "ananya@example.com",
    phone: "+91 98250 11223",
    role: "customer",
  },
  {
    id: "u-owner-1",
    name: "Rajesh Patel",
    email: "rajesh@shreeplots.in",
    phone: "+91 98250 44556",
    role: "owner",
  },
  {
    id: "u-owner-2",
    name: "Meera Desai",
    email: "meera@palaceresort.in",
    phone: "+91 98250 77889",
    role: "owner",
  },
  {
    id: "u-admin-1",
    name: "Admin",
    email: "admin@mandapam.in",
    phone: "+91 90161 80583",
    role: "admin",
  },
];

export const SEED_VENUES: Venue[] = [
  {
    id: "v-001",
    name: "Shree Party Plot",
    ownerId: "u-owner-1",
    ownerName: "Rajesh Patel",
    type: "Party Plot",
    city: "Ahmedabad",
    area: "Bodakdev",
    address: "Shree Party Plot, SG Highway, Bodakdev, Ahmedabad – 380054",
    description:
      "A sprawling open-air party plot ideal for grand Indian weddings. Lush green lawns, dedicated mandap area, ample parking for 200+ cars, in-house decoration team and a fully equipped kitchen for catering. Two decades of hosting memorable celebrations.",
    capacityMin: 300,
    capacityMax: 1200,
    priceWeekday: 85000,
    priceWeekend: 125000,
    coverImage:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc4?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: ["Bridal Room", "Power Backup", "Valet Parking", "In-house Decor", "Lawn", "Kitchen"],
    indoor: false,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 2,
    ac: false,
    bar: false,
    dj: true,
    packages: [
      {
        id: "p-001-silver",
        name: "Silver Celebration",
        description: "Venue + basic decor + 1 bridal room + 2 waiters per 100 guests.",
        price: 125000,
        includes: ["Venue rental", "Basic floral decor", "Bridal room", "Service staff"],
      },
      {
        id: "p-001-gold",
        name: "Gold Royal",
        description: "Venue + premium decor + catering for 500 guests + DJ + 2 bridal rooms.",
        price: 325000,
        includes: [
          "Venue rental",
          "Premium theme decor",
          "Veg catering for 500",
          "DJ + light sound",
          "2 Bridal rooms",
          "Valet parking",
        ],
      },
      {
        id: "p-001-platinum",
        name: "Platinum Mandapam",
        description: "All-inclusive wedding with stage, mandap, lighting, catering, decor & hospitality.",
        price: 625000,
        includes: [
          "Venue rental (full day)",
          "Designer mandap + stage",
          "Veg + Jain catering for 800",
          "Premium DJ + LED wall",
          "3 Bridal suites",
          "Hosts & coordinators",
        ],
      },
    ],
    rating: 4.6,
    reviewsCount: 142,
    reviews: [
      {
        id: "r-001-1",
        customerName: "Hardik Mehta",
        rating: 5,
        comment: "Hosted our wedding here in December — flawless coordination and gorgeous decor!",
        date: pastDate(40),
        eventType: "Wedding",
      },
      {
        id: "r-001-2",
        customerName: "Pooja Shah",
        rating: 4,
        comment: "Great space, parking was a bit tight on weekend evenings but overall lovely.",
        date: pastDate(15),
        eventType: "Reception",
      },
    ],
    blockedDates: [futureDate(10), futureDate(20), futureDate(45)],
    status: "approved",
    verified: true,
    createdAt: pastDate(220),
  },
  {
    id: "v-002",
    name: "The Grand Palace Resort",
    ownerId: "u-owner-2",
    ownerName: "Meera Desai",
    type: "Resort",
    city: "Udaipur",
    area: "Lake Pichola",
    address: "The Grand Palace Resort, Lake Pichola Road, Udaipur – 313001",
    description:
      "A heritage-style palace resort on the banks of Lake Pichola. 40 luxury suites, lakeside lawns, grand courtyard, spa, multi-cuisine restaurant, and a dedicated wedding concierge team. Perfect for destination weddings.",
    capacityMin: 100,
    capacityMax: 600,
    priceWeekday: 250000,
    priceWeekend: 425000,
    coverImage:
      "https://images.unsplash.com/photo-1542314831-068cd1fbfe1c?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1542314831-068cd1fbfe1c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1561501900-3705fa8a4f5f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: [
      "40 Luxury Suites",
      "Lakeside Lawn",
      "Spa & Wellness",
      "Swimming Pool",
      "Multi-cuisine Restaurant",
      "Airport Pickup",
      "Wedding Concierge",
    ],
    indoor: true,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 40,
    ac: true,
    bar: true,
    dj: true,
    packages: [
      {
        id: "p-002-lakeside",
        name: "Lakeside Vows",
        description: "2-day resort booking with lakeside mandap, 30 suites, decor & welcome dinner.",
        price: 1850000,
        includes: [
          "2-day resort block",
          "Lakeside mandap",
          "30 luxury suites",
          "Welcome dinner",
          "Decor & floral",
        ],
      },
      {
        id: "p-002-royal",
        name: "Royal Destination Wedding",
        description: "3-day royal wedding with mehendi, sangeet, wedding & reception. All inclusive.",
        price: 3450000,
        includes: [
          "3-day resort buyout",
          "Mehendi + Sangeet + Wedding + Reception",
          "40 suites",
          "Multi-cuisine catering (4 functions)",
          "DJ + Live band",
          "Photography coordination",
        ],
      },
    ],
    rating: 4.9,
    reviewsCount: 89,
    reviews: [
      {
        id: "r-002-1",
        customerName: "Aditya Rathi",
        rating: 5,
        comment: "Destination wedding of our dreams. Lake view at sunset was magical.",
        date: pastDate(70),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(5), futureDate(15), futureDate(60), futureDate(120)],
    status: "approved",
    verified: true,
    createdAt: pastDate(310),
  },
  {
    id: "v-003",
    name: "Royal Banquet Hall",
    ownerId: "u-owner-1",
    ownerName: "Rajesh Patel",
    type: "Banquet Hall",
    city: "Ahmedabad",
    area: "Vastrapur",
    address: "Royal Banquet, Iscon Cross Road, Vastrapur, Ahmedabad – 380015",
    description:
      "Fully air-conditioned banquet hall with pillar-less design, crystal chandeliers, and seating for 800. Ideal for receptions, engagements, birthdays, and corporate galas.",
    capacityMin: 100,
    capacityMax: 800,
    priceWeekday: 65000,
    priceWeekend: 95000,
    coverImage:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49cd?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49cd?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc4?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: ["AC Hall", "Crystal Chandeliers", "Stage", "Bridal Room", "Power Backup", "Elevator"],
    indoor: true,
    outdoor: false,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 1,
    ac: true,
    bar: false,
    dj: true,
    packages: [
      {
        id: "p-003-reception",
        name: "Reception Special",
        description: "Hall + stage + decor + catering for 300 guests.",
        price: 185000,
        includes: ["Hall rental", "Stage setup", "Floral decor", "Veg catering for 300"],
      },
      {
        id: "p-003-engagement",
        name: "Engagement Combo",
        description: "Hall + intimate stage + decor + catering for 150.",
        price: 125000,
        includes: ["Hall rental", "Intimate stage", "Light decor", "Veg catering for 150"],
      },
    ],
    rating: 4.4,
    reviewsCount: 211,
    reviews: [
      {
        id: "r-003-1",
        customerName: "Sneha Iyer",
        rating: 4,
        comment: "Beautiful AC hall, great for receptions. Staff was cooperative.",
        date: pastDate(25),
        eventType: "Reception",
      },
    ],
    blockedDates: [futureDate(3), futureDate(25)],
    status: "approved",
    verified: true,
    createdAt: pastDate(180),
  },
  {
    id: "v-004",
    name: "Green Meadows Lawn",
    ownerId: "u-owner-2",
    ownerName: "Meera Desai",
    type: "Lawn",
    city: "Pune",
    area: "Baner",
    address: "Green Meadows, Baner-Balewadi Road, Baner, Pune – 411045",
    description:
      "Two acres of manicured lawn surrounded by tall trees. Open-air venue perfect for haldi, sangeet, and day weddings. In-house caterer and decorator available.",
    capacityMin: 200,
    capacityMax: 1000,
    priceWeekday: 55000,
    priceWeekend: 85000,
    coverImage:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc4?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc4?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: ["2-acre Lawn", "Open-air Mandap", "Green Room", "Parking 150 cars", "Power Backup"],
    indoor: false,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 1,
    ac: false,
    bar: false,
    dj: true,
    packages: [
      {
        id: "p-004-haldi",
        name: "Haldi & Sangeet",
        description: "Lawn + decor + catering for 200 guests (half day).",
        price: 95000,
        includes: ["Lawn rental (4 hours)", "Haldi decor", "Veg catering for 200", "DJ"],
      },
      {
        id: "p-004-daywedding",
        name: "Day Wedding",
        description: "Lawn + mandap + decor + catering for 500 (full day).",
        price: 215000,
        includes: ["Lawn rental (full day)", "Mandap", "Premium decor", "Veg catering for 500", "DJ"],
      },
    ],
    rating: 4.5,
    reviewsCount: 67,
    reviews: [
      {
        id: "r-004-1",
        customerName: "Rohan Kulkarni",
        rating: 5,
        comment: "Lush green lawn, perfect for our day wedding. Loved every minute.",
        date: pastDate(50),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(7), futureDate(30)],
    status: "approved",
    verified: true,
    createdAt: pastDate(150),
  },
  {
    id: "v-005",
    name: "Heritage Haveli Wedding Venue",
    ownerId: "u-owner-1",
    ownerName: "Rajesh Patel",
    type: "Wedding Venue",
    city: "Jaipur",
    area: "Amer",
    address: "Heritage Haveli, Amer Road, Jaipur – 302002",
    description:
      "A restored 18th-century haveli with rooftop courtyard, jharokha views, and traditional Rajasthani decor. Perfect for intimate royal weddings and pre-wedding shoots.",
    capacityMin: 50,
    capacityMax: 350,
    priceWeekday: 175000,
    priceWeekend: 285000,
    coverImage:
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1561501900-3705fa8a4f5f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: [
      "Rooftop Courtyard",
      "Heritage Architecture",
      "Royal Decor",
      "Folk Performance Setup",
      "Photography Friendly",
      "8 Heritage Rooms",
    ],
    indoor: true,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 8,
    ac: true,
    bar: true,
    dj: false,
    packages: [
      {
        id: "p-005-intimate",
        name: "Intimate Royal Wedding",
        description: "Haveli booking for 1 day, mandap, decor, catering for 150.",
        price: 625000,
        includes: ["Haveli block (1 day)", "Royal mandap", "Traditional decor", "Catering for 150"],
      },
    ],
    rating: 4.8,
    reviewsCount: 38,
    reviews: [
      {
        id: "r-005-1",
        customerName: "Isha Agarwal",
        rating: 5,
        comment: "Felt like a royal wedding. The haveli is gorgeous for photography.",
        date: pastDate(35),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(2), futureDate(18), futureDate(75)],
    status: "approved",
    verified: true,
    createdAt: pastDate(120),
  },
  {
    id: "v-006",
    name: "Celestial Convention Centre",
    ownerId: "u-owner-2",
    ownerName: "Meera Desai",
    type: "Banquet Hall",
    city: "Bengaluru",
    area: "Whitefield",
    address: "Celestial Convention Centre, ITPL Road, Whitefield, Bengaluru – 560066",
    description:
      "Modern convention centre with three connected halls, LED wall, professional lighting, and a 600-car parking garage. Suitable for large weddings, corporate events, and exhibitions.",
    capacityMin: 300,
    capacityMax: 1800,
    priceWeekday: 145000,
    priceWeekend: 215000,
    coverImage:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: [
      "3 Connected Halls",
      "LED Wall",
      "Pro Lighting",
      "600-car Parking",
      "Green Rooms",
      "Café Lounge",
    ],
    indoor: true,
    outdoor: false,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 4,
    ac: true,
    bar: true,
    dj: true,
    packages: [
      {
        id: "p-006-mega",
        name: "Mega Wedding",
        description: "All 3 halls + LED + decor + catering for 1200.",
        price: 925000,
        includes: ["All 3 halls", "LED wall", "Pro lighting", "Decor", "Catering for 1200"],
      },
      {
        id: "p-006-corporate",
        name: "Corporate Gala",
        description: "Single hall + AV + catering for 400.",
        price: 285000,
        includes: ["Single hall", "AV setup", "Catering for 400", "Stage"],
      },
    ],
    rating: 4.5,
    reviewsCount: 156,
    reviews: [
      {
        id: "r-006-1",
        customerName: "Vikram Rao",
        rating: 4,
        comment: "Massive venue, great for big weddings. AV setup was top class.",
        date: pastDate(20),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(1), futureDate(8), futureDate(40)],
    status: "approved",
    verified: true,
    createdAt: pastDate(95),
  },
  {
    id: "v-007",
    name: "Sunrise Garden Marriage Plot",
    ownerId: "u-owner-1",
    ownerName: "Rajesh Patel",
    type: "Marriage Plot",
    city: "Surat",
    area: "Adajan",
    address: "Sunrise Garden, Adajan-Dummas Road, Surat – 395009",
    description:
      "Spacious marriage plot with concrete flooring, dedicated mandap area, kitchen block, and ample parking. Best value for community weddings.",
    capacityMin: 400,
    capacityMax: 1500,
    priceWeekday: 45000,
    priceWeekend: 75000,
    coverImage:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: ["Concrete Floor", "Mandap Area", "Kitchen Block", "Parking 300 cars", "Toilets"],
    indoor: false,
    outdoor: true,
    parking: true,
    catering: false,
    decoration: false,
    rooms: 0,
    ac: false,
    bar: false,
    dj: false,
    packages: [
      {
        id: "p-007-basic",
        name: "Plot Rental Only",
        description: "Bare plot rental — bring your own decorator and caterer.",
        price: 75000,
        includes: ["Plot rental (full day)", "Parking", "Toilets", "Power connection"],
      },
    ],
    rating: 4.1,
    reviewsCount: 48,
    reviews: [
      {
        id: "r-007-1",
        customerName: "Jignesh Patel",
        rating: 4,
        comment: "Good value for the price. Basic but spacious.",
        date: pastDate(12),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(14)],
    status: "approved",
    verified: false,
    createdAt: pastDate(60),
  },
  {
    id: "v-008",
    name: "Beachside Bliss Resort",
    ownerId: "u-owner-2",
    ownerName: "Meera Desai",
    type: "Resort",
    city: "Goa",
    area: "Candolim",
    address: "Beachside Bliss, Candolim Beach Road, Goa – 403515",
    description:
      "Beachfront resort with private beach access, infinity pool, and 25 sea-view cottages. The perfect setting for a bohemian beach wedding.",
    capacityMin: 80,
    capacityMax: 400,
    priceWeekday: 195000,
    priceWeekend: 325000,
    coverImage:
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1561501900-3705fa8a4f5f?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1fbfe1c?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: [
      "Private Beach",
      "Infinity Pool",
      "25 Sea-view Cottages",
      "Beach Bar",
      "Spa",
      "Water Sports",
    ],
    indoor: true,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 25,
    ac: true,
    bar: true,
    dj: true,
    packages: [
      {
        id: "p-008-beach",
        name: "Beach Wedding",
        description: "Beach mandap + 20 cottages + decor + catering for 200.",
        price: 1450000,
        includes: [
          "Beach mandap",
          "20 sea-view cottages",
          "Boho decor",
          "Catering for 200",
          "DJ + sunset party",
        ],
      },
    ],
    rating: 4.7,
    reviewsCount: 54,
    reviews: [
      {
        id: "r-008-1",
        customerName: "Karan Malhotra",
        rating: 5,
        comment: "Beach wedding was surreal. Team handled everything end to end.",
        date: pastDate(28),
        eventType: "Wedding",
      },
    ],
    blockedDates: [futureDate(11), futureDate(35), futureDate(90)],
    status: "approved",
    verified: true,
    createdAt: pastDate(140),
  },
  // A pending venue for admin approval demo
  {
    id: "v-009",
    name: "Lavish Lawns & Banquet",
    ownerId: "u-owner-1",
    ownerName: "Rajesh Patel",
    type: "Banquet Hall",
    city: "Mumbai",
    area: "Andheri West",
    address: "Lavish Lawns, Veera Desai Road, Andheri West, Mumbai – 400053",
    description:
      "Brand new banquet hall with attached lawn, modern interiors, and high-end lighting. Awaiting platform approval.",
    capacityMin: 150,
    capacityMax: 700,
    priceWeekday: 125000,
    priceWeekend: 185000,
    coverImage:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    photos: [
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1000&q=80",
    ],
    amenities: ["AC Hall", "Attached Lawn", "LED Wall", "Bridal Suite", "Valet Parking"],
    indoor: true,
    outdoor: true,
    parking: true,
    catering: true,
    decoration: true,
    rooms: 2,
    ac: true,
    bar: false,
    dj: true,
    packages: [
      {
        id: "p-009-premium",
        name: "Premium Combo",
        description: "Hall + lawn + decor + catering for 500.",
        price: 425000,
        includes: ["Hall + lawn", "Premium decor", "Catering for 500", "LED + DJ"],
      },
    ],
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    blockedDates: [],
    status: "pending",
    verified: false,
    createdAt: pastDate(2),
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "b-001",
    venueId: "v-001",
    venueName: "Shree Party Plot",
    venueCity: "Ahmedabad",
    packageId: "p-001-gold",
    packageName: "Gold Royal",
    customerId: "u-cust-1",
    customerName: "Ananya Sharma",
    customerPhone: "+91 98250 11223",
    customerEmail: "ananya@example.com",
    eventDate: futureDate(45),
    eventType: "Wedding",
    guestCount: 500,
    totalAmount: 325000,
    bookingAmount: 65000,
    status: "confirmed",
    paymentRef: "VS-PAY-9F2A1",
    createdAt: pastDate(5),
    specialRequests: "Need extra parking for 50 cars. Bride arrival by horse at 7 PM.",
  },
  {
    id: "b-002",
    venueId: "v-003",
    venueName: "Royal Banquet Hall",
    venueCity: "Ahmedabad",
    packageId: "p-003-reception",
    packageName: "Reception Special",
    customerId: "u-cust-1",
    customerName: "Ananya Sharma",
    customerPhone: "+91 98250 11223",
    customerEmail: "ananya@example.com",
    eventDate: futureDate(15),
    eventType: "Reception",
    guestCount: 300,
    totalAmount: 185000,
    bookingAmount: 37000,
    status: "confirmed",
    paymentRef: "VS-PAY-7H1B9",
    createdAt: pastDate(8),
  },
  {
    id: "b-003",
    venueId: "v-002",
    venueName: "The Grand Palace Resort",
    venueCity: "Udaipur",
    packageId: "p-002-lakeside",
    packageName: "Lakeside Vows",
    customerId: "u-cust-1",
    customerName: "Rohit Verma",
    customerPhone: "+91 98250 99887",
    customerEmail: "rohit@example.com",
    eventDate: pastDate(20),
    eventType: "Wedding",
    guestCount: 250,
    totalAmount: 1850000,
    bookingAmount: 370000,
    status: "completed",
    paymentRef: "VS-PAY-3C7D2",
    createdAt: pastDate(85),
  },
  {
    id: "b-004",
    venueId: "v-004",
    venueName: "Green Meadows Lawn",
    venueCity: "Pune",
    packageId: "p-004-haldi",
    packageName: "Haldi & Sangeet",
    customerId: "u-cust-1",
    customerName: "Priya Nair",
    customerPhone: "+91 98250 66554",
    customerEmail: "priya@example.com",
    eventDate: futureDate(7),
    eventType: "Sangeet / Haldi",
    guestCount: 200,
    totalAmount: 95000,
    bookingAmount: 19000,
    status: "confirmed",
    paymentRef: "VS-PAY-5K4M8",
    createdAt: pastDate(3),
  },
  {
    id: "b-005",
    venueId: "v-006",
    venueName: "Celestial Convention Centre",
    venueCity: "Bengaluru",
    packageId: "p-006-corporate",
    packageName: "Corporate Gala",
    customerId: "u-cust-1",
    customerName: "TechCorp India",
    customerPhone: "+91 80 4567 8900",
    customerEmail: "events@techcorp.in",
    eventDate: futureDate(30),
    eventType: "Corporate",
    guestCount: 400,
    totalAmount: 285000,
    bookingAmount: 57000,
    status: "pending_payment",
    paymentRef: "VS-PAY-PENDING",
    createdAt: pastDate(1),
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: "c-1",
    code: "MANDAPAM1000",
    description: "Flat ₹1,000 off on bookings above ₹50,000",
    type: "flat",
    value: 1000,
    minAmount: 50000,
    active: true,
  },
  {
    id: "c-2",
    code: "EARLYBIRD10",
    description: "10% off (max ₹15,000) on bookings made 60+ days in advance",
    type: "percent",
    value: 10,
    minAmount: 75000,
    active: true,
  },
  {
    id: "c-3",
    code: "WEDDING5000",
    description: "Flat ₹5,000 off on destination weddings above ₹5,00,000",
    type: "flat",
    value: 5000,
    minAmount: 500000,
    active: true,
  },
];

export const SEED_DISPUTES: Dispute[] = [
  {
    id: "d-1",
    bookingId: "b-003",
    customerName: "Rohit Verma",
    venueName: "The Grand Palace Resort",
    subject: "Decor shortfall",
    description:
      "Promised 200 roses for mandap, received only 80. Requesting ₹15,000 refund.",
    status: "investigating",
    raisedAt: pastDate(15),
  },
  {
    id: "d-2",
    bookingId: "b-002",
    customerName: "Ananya Sharma",
    venueName: "Royal Banquet Hall",
    subject: "AC not working in bridal room",
    description:
      "Bridal room AC was non-functional during the event. Requesting partial refund.",
    status: "open",
    raisedAt: pastDate(2),
  },
];

export const CITIES = [
  "Ahmedabad",
  "Bengaluru",
  "Goa",
  "Jaipur",
  "Mumbai",
  "Pune",
  "Surat",
  "Udaipur",
];

export const EVENT_TYPES = [
  "Wedding",
  "Reception",
  "Engagement",
  "Birthday",
  "Corporate",
  "Anniversary",
  "Sangeet / Haldi",
] as const;

export const VENUE_TYPES = [
  "Marriage Plot",
  "Banquet Hall",
  "Party Plot",
  "Lawn",
  "Resort",
  "Wedding Venue",
] as const;

export const ALL_AMENITIES = [
  "AC Hall",
  "Bridal Room",
  "Bridal Suite",
  "Power Backup",
  "Valet Parking",
  "In-house Decor",
  "Lawn",
  "Kitchen",
  "LED Wall",
  "DJ",
  "Bar",
  "Spa",
  "Swimming Pool",
  "Beach Access",
  "Heritage Architecture",
  "Photography Friendly",
  "Multi-cuisine Restaurant",
];
